version: '1'
services:
   mysql:
     image: mysql:5.7
     container_name: sqlcont
     ports:
       - "3306:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=petclinic
       - MYSQL_DATABASE=petclinic
     volumes:
       - "./conf.d:/etc/mysql/conf.d:ro"
   app1:
     build:
       context: .
       dockerfile: dockerfile
     container_name: z-app
     ports:
       - "800:800"
     environment:
       my-db: mysql
       SPRING_PROFILES_ACTIVE: mysql
       SPRING_DATASOURCE_URL: jdbc:mysql://mysql/petclinic
       MYSQL_ROOT_PASSWORD: petclinic
       MYSQL_DATABASE: petclinic
     restart: always
     links:
       - mysql

