FROM maven:3.2-jdk-8 as my_app
WORKDIR /app
RUN git clone https://github.com/spring-projects/spring-petclinic.git
WORKDIR /app/spring-petclinic
RUN mvn package

FROM openjdk:8-jre-alpine
ENV artifact spring-petclinic-2.2.0.jar
WORKDIR /app
COPY --from=my_app /app/spring-petclinic/target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar /app
EXPOSE 8080
ENTRYPOINT ["sh", "-c"]
CMD ["java -jar /app/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar"]
